name: Build & Push Frontend + Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out code
      - name: Check out
        uses: actions/checkout@v3

      # 2. Log into Docker Hub (or any Docker registry)
      - name: Log in to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build & push the frontend image (Next.js + Nginx)
      - name: Build & push frontend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ascendantwiki-fe:latest

      # 4. Build & push the backend image (Spring Boot)
      - name: Build & push backend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ascendantwiki-be:latest
